import { useEffect, useState } from 'react';
import type { ServiceWorkerRegistration } from './vite-env';
import { useData } from './useData';
import { Dashboard, Sessions, Live, Hands, Rooms, Expenses, Tips, Bankroll, Tools, Settings } from './pages';
import type { FilterModel, Theme } from './types';
export type View='dashboard'|'sessions'|'live'|'hands'|'rooms'|'expenses'|'tips'|'bankroll'|'tools'|'settings';
const navigation:{id:View;label:string;icon:string}[]=[{id:'dashboard',label:'Dashboard',icon:'⌂'},{id:'sessions',label:'Sessions',icon:'≡'},{id:'live',label:'Live',icon:'●'},{id:'hands',label:'Hands',icon:'♠'},{id:'rooms',label:'Rooms',icon:'⌖'},{id:'expenses',label:'Expenses',icon:'−'},{id:'tips',label:'Tips',icon:'♥'},{id:'bankroll',label:'Bankroll',icon:'▰'},{id:'tools',label:'Tools',icon:'◇'},{id:'settings',label:'Settings',icon:'⚙'}];
function Nav({items,active,go,hasLive}:{items:typeof navigation;active:View;go:(v:View)=>void;hasLive:boolean}){return <nav>{items.map(x=><button key={x.id} className={active===x.id?'active':''} onClick={()=>go(x.id)}><span className="nav-icon">{x.icon}{x.id==='live'&&hasLive&&<i/>}</span><span>{x.id==='live'&&hasLive?'Playing':x.label}</span></button>)}</nav>}
export default function App(){const{data,loading}=useData();const valid=navigation.map(x=>x.id);const query=new URLSearchParams(location.search).get('view') as View;const[view,setView]=useState<View>(valid.includes(query)?query:'dashboard');const[filter,setFilter]=useState<FilterModel>({period:'all',roomId:'',query:'',result:'all'});const[clock,setClock]=useState(new Date());const[update,setUpdate]=useState<ServiceWorkerRegistration|null>(null);const theme=(data.settings.find(x=>x.key==='theme')?.value??'dark') as Theme;const active=data.sessions.find(x=>x.active);useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);useEffect(()=>{const id=setInterval(()=>setClock(new Date()),60000);return()=>clearInterval(id)},[]);useEffect(()=>{const fn=(e:Event)=>setUpdate((e as CustomEvent<ServiceWorkerRegistration>).detail);addEventListener('ptracker:update',fn);return()=>removeEventListener('ptracker:update',fn)},[]);if(loading)return <main className="splash"><span className="brand-mark">P</span><strong>PTracker</strong><small>Opening local database…</small></main>;const go=(v:View)=>{setView(v);history.replaceState(null,'',v==='dashboard'?location.pathname:`?view=${v}`);scrollTo({top:0,behavior:'smooth'})};const brand=<button className="brand" onClick={()=>go('dashboard')}><span className="brand-mark">P</span><span className="brand-copy"><b>PTracker</b><time>{clock.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></span></button>;return <div className="app-shell"><aside className="rail">{brand}<Nav items={navigation} active={view} go={go} hasLive={!!active}/></aside><main className="main"><header className="topbar"><div className="mobile-brand">{brand}</div></header>{view==='dashboard'&&<Dashboard data={data} filter={filter} setFilter={setFilter} go={go}/>} {view==='sessions'&&<Sessions data={data} filter={filter} setFilter={setFilter} go={go}/>} {view==='live'&&<Live data={data} active={active} go={go}/>} {view==='hands'&&<Hands data={data} active={active}/>} {view==='rooms'&&<Rooms data={data}/>} {view==='expenses'&&<Expenses data={data}/>} {view==='tips'&&<Tips data={data}/>} {view==='bankroll'&&<Bankroll data={data}/>} {view==='tools'&&<Tools data={data} active={active}/>} {view==='settings'&&<Settings data={data} theme={theme}/>}</main><div className="mobile-nav"><Nav items={navigation} active={view} go={go} hasLive={!!active}/></div>{update&&<div className="update-toast"><strong>Update ready</strong><button onClick={()=>{update.waiting?.postMessage({type:'SKIP_WAITING'});location.reload()}}>Update</button></div>}</div>}
